### ISSUE TITLE
'ChatBotModel' object has no attribute 'beam_path'

### ISSUE THREAD

**Issue by phage-nz** [nikhilaravi/Flo#1]
Hi,

After completing the first epoch of training and the evaluation is completed I get the following error:

> Iter 1000: loss 4.68104373932, time 0.438112020493
Traceback (most recent call last):
  File "chatbot.py", line 425, in <module>
    main()
  File "chatbot.py", line 420, in main
    train()
  File "chatbot.py", line 182, in train
    _eval_test_set(sess, model, test_buckets)
  File "chatbot.py", line 145, in _eval_test_set
    decoder_masks, bucket_id, True)
  File "chatbot.py", line 85, in run_step
    output_feed = [model.beam_path[bucket_id]]  # Loss for this batch.
AttributeError: 'ChatBotModel' object has no attribute 'beam_path'

Have you run into this error yourself?

Thanks!

**Comment by phage-nz** [comment]
Look to have worked it out.

Line 144:
`_, step_loss, _ = run_step(sess, model, encoder_inputs, decoder_inputs, decoder_masks, bucket_id, True, eval_test=True)`

Line 59:
`def run_step(sess, model, encoder_inputs, decoder_inputs, decoder_masks, bucket_id, forward_only, eval_test=False):`

Line 84:
`if config.BEAM_SEARCH and eval_test == False:`

Unsure if this is as you intended.
